<a href="https://colab.research.google.com/github/Bibhuti-MLAI/Python-Coding-Interview/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])

In [ ]:
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
print(a)

[1 2 3]


In [ ]:
b= np.array([[1,2,3],[4,5,6]])

In [ ]:
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c=np.array([[[1,2],[3,4],[5,6]]])

In [ ]:
c

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
lp = np.linspace(-10,10,10)
print(lp)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a1= np.arange(10)
a2 = np.arange(12,dtype =float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
#ndln
a2.ndim

2

In [ ]:
a1.shape

(10,)

In [ ]:
a2.shape

(3, 4)

In [ ]:
a3.shape

(2, 2, 2)

In [ ]:
 a3.size

8

In [ ]:
a1.itemsize

8

In [ ]:
a1.dtype

dtype('int64')

Changing Data types

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3.dtype

dtype('int64')

In [ ]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operation

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
a1*3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [ ]:
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
a2 >5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a1>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a1==2

array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)

In [ ]:
a1

array([[30., 79., 39.],
       [66., 59., 89.],
       [72., 37.,  0.]])

In [ ]:
np.max(a1)

np.float64(89.0)

In [ ]:
np.prod(a1)

np.float64(0.0)

In [ ]:
np.var(a1,axis=1)

array([453.55555556, 164.22222222, 864.22222222])

In [ ]:
np.mean(a1,axis=0)

array([56.        , 58.33333333, 42.66666667])

In [ ]:
np.sin(a1)

array([[-0.98803162, -0.44411267,  0.96379539],
       [-0.02655115,  0.63673801,  0.86006941],
       [ 0.25382336, -0.64353813,  0.        ]])

In [ ]:
a2 = np.random.random((3,4))
a3 = np.random.random((4,3))

In [ ]:
np.dot(a2,a3)

array([[1.69339147, 1.5128126 , 1.14393484],
       [1.26159363, 0.91280491, 1.03620689],
       [1.16510189, 1.03347425, 1.07184132]])

Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[0]

np.int64(0)

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(a2[2,3])

11


In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1][0][1]

np.int64(5)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5]

array([2, 3, 4])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3=np.arange(27).reshape(3,3,3)

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0][1]

array([3, 4, 5])

Advance

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Stacking

In [ ]:
a2.transpose

<function ndarray.transpose>

In [ ]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])