<a href="https://colab.research.google.com/github/Bibhuti-MLAI/Python-Coding-Interview/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
print(a)

[1 2 3]


In [6]:
b= np.array([[1,2,3],[4,5,6]])

In [7]:
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
c=np.array([[[1,2],[3,4],[5,6]]])

In [9]:
c

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [10]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
lp = np.linspace(-10,10,10)
print(lp)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
a1= np.arange(10)
a2 = np.arange(12,dtype =float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
#ndln
a2.ndim

2

In [17]:
a1.shape

(10,)

In [18]:
a2.shape

(3, 4)

In [19]:
a3.shape

(2, 2, 2)

In [20]:
 a3.size

8

In [21]:
a1.itemsize

8

In [22]:
a1.dtype

dtype('int64')

Changing Data types

In [23]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [24]:
a3.dtype

dtype('int64')

In [25]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operation

In [26]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [27]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [28]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [30]:
a1*3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [31]:
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [32]:
a2 >5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [33]:
a1>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [34]:
a1==2

array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [35]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [36]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [37]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)

In [38]:
a1

array([[ 97.,  91., 100.],
       [ 14.,  29.,  85.],
       [ 76.,  74.,   3.]])

In [39]:
np.max(a1)

np.float64(100.0)

In [40]:
np.prod(a1)

np.float64(513954475944000.0)

In [41]:
np.var(a1,axis=1)

array([  14.        ,  933.55555556, 1152.66666667])

In [42]:
np.mean(a1,axis=0)

array([62.33333333, 64.66666667, 62.66666667])

In [43]:
np.sin(a1)

array([[ 0.37960774,  0.10598751, -0.50636564],
       [ 0.99060736, -0.66363388, -0.17607562],
       [ 0.56610764, -0.98514626,  0.14112001]])

In [44]:
a2 = np.random.random((3,4))
a3 = np.random.random((4,3))

In [45]:
np.dot(a2,a3)

array([[0.63553277, 1.14531241, 1.21811925],
       [1.01951245, 1.59710991, 1.98651568],
       [1.04187982, 1.29885502, 1.63118543]])

Indexing and Slicing

In [46]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a1[0]

np.int64(0)

In [48]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
print(a2[2,3])

11


In [50]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [51]:
a3[1][0][1]

np.int64(5)

In [52]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a1[2:5]

array([2, 3, 4])

In [54]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [55]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
a2[:,2]

array([ 2,  6, 10])

In [57]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [58]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [59]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [60]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [61]:
a3=np.arange(27).reshape(3,3,3)

In [62]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [63]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [64]:
a3[0][1]

array([3, 4, 5])

Advance

In [65]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [67]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [68]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Stacking

In [70]:
a2.transpose

<function ndarray.transpose>

In [71]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [73]:
import numpy as np
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[29, 20, 92, 91],
       [91, 61, 62, 20],
       [92, 63, 57, 56],
       [99, 67, 69, 17],
       [39, 92, 37, 31],
       [75, 11, 65, 21]])

In [74]:
a >50

array([[False, False,  True,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False,  True, False, False],
       [ True, False,  True, False]])

In [75]:
a[a>50]

array([92, 91, 91, 61, 62, 92, 63, 57, 56, 99, 67, 69, 92, 75, 65])

In [77]:
#find ut even number
a[a%2==0]

array([20, 92, 62, 20, 92, 56, 92])

In [78]:
a[(a%2==0) & (a%2 == 0)]

array([20, 92, 62, 20, 92, 56, 92])

In [79]:
a[a%7 !=0]

array([29, 20, 92, 61, 62, 20, 92, 57, 99, 67, 69, 17, 39, 92, 37, 31, 75,
       11, 65])

In [80]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

In [81]:
a+b

array([[ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

Maths with numpy

In [85]:
#sigmoid
def sigmoid(array):
  return 1/(1+np.exp((-array)))
a = np.arange(100)

In [86]:
sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661,
       0.9999546 , 0.9999833 , 0.99999386, 0.99999774, 0.99999917,
       0.99999969, 0.99999989, 0.99999996, 0.99999998, 0.99999999,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

In [87]:
#mean squared error
actual = np.random.randint(1,50,25)
pred = np.random.randint(1,50,25)

In [89]:
actual

array([37, 44,  6, 23,  1,  3, 48, 46, 38, 15, 24,  3, 43,  5, 12, 37, 19,
       27, 45, 31, 21, 49, 11, 28, 31])

In [90]:
pred

array([21,  2, 31,  4, 17,  3,  4, 12, 14, 10,  1, 44, 34, 13,  6,  6, 20,
        9,  2, 11, 38, 23, 35, 47,  6])

In [92]:
def mse(actual,pred):
  return np.mean((actual-pred)**2)
mse (actual,pred)

np.float64(616.32)

In [ ]:
#binary cross entropy