<a href="https://colab.research.google.com/github/Bibhuti-MLAI/Python-Coding-Interview/blob/main/Python_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
a=10
b=20
print(a+b)

30


In [37]:
first_name='Bibhuti'
last_name='Sahu'

In [38]:
print("My First name if {} and my Last is {}".format(first_name,last_name))

My First name if Bibhuti and my Last is Sahu


In [39]:
lst=['Math',10,20, 3,40]

In [40]:
type(lst)

list

In [41]:
lst.append('Bibhuti')

In [42]:
lst

['Math', 10, 20, 3, 40, 'Bibhuti']

In [43]:
lst.pop

<function list.pop(index=-1, /)>

In [44]:
lst

['Math', 10, 20, 3, 40, 'Bibhuti']

In [45]:
lst.insert(1,'Bhusan')

In [46]:
lst

['Math', 'Bhusan', 10, 20, 3, 40, 'Bibhuti']

In [47]:
lst.append(['chem','phy'])

In [48]:
lst

['Math', 'Bhusan', 10, 20, 3, 40, 'Bibhuti', ['chem', 'phy']]

In [49]:
#finding prime number
num=int(input("Enter the number:"))
if num>1:
    for i in range(2,num):
        if (num%i)==0:
            print(num,"is not a prime number")
            break
    else:
        print(num,"is a prime number")

Enter the number:20
20 is not a prime number


In [50]:
for num in range(2,20):
  for i in range (2,num):
    if num%i==0:
      break
  else:
    print(num)

2
3
5
7
11
13
17
19


In [51]:
#sorting elements in list
list=[1,5,78,6,4,8,9,57,6,45,75,89,65,25,47,56]
list_sort =[]
while list:
  minimum=list[0]
  for x in list:
    if x < minimum:
      minimum=x
  list_sort.append(minimum)
  list.remove(minimum)
print(list_sort)


[1, 4, 5, 6, 6, 8, 9, 25, 45, 47, 56, 57, 65, 75, 78, 89]


In [52]:
#sorting elements in list
list=[1,5,78,6,4,8,9,57,6,45,75,89,65,25,47,56]
list_sort =[]
while list:
  minimum=list[0]
  for x in list:
    if minimum>x:
      minimum=x
  list_sort.append(minimum)
  list.remove(minimum)
print(list_sort)

[1, 4, 5, 6, 6, 8, 9, 25, 45, 47, 56, 57, 65, 75, 78, 89]


In [53]:
#dictionary learning
my_dict={"car1":"Audi","car2":"Mercedese","car3":"bmw"}
my_dict
type(my_dict)

dict

In [54]:
my_dict['car1']

'Audi'

In [55]:
for x in my_dict.items():
  print(x)

('car1', 'Audi')
('car2', 'Mercedese')
('car3', 'bmw')


In [56]:
my_dict["car4"]="maruti"


#NumPy Tutorial


In [57]:
import numpy as np
list_sort
arr=np.array(list_sort)
arr
type(arr)
arr.shape

(16,)

In [58]:
arr

array([ 1,  4,  5,  6,  6,  8,  9, 25, 45, 47, 56, 57, 65, 75, 78, 89])

In [60]:
arr.reshape

<function ndarray.reshape>

In [61]:
arr

array([ 1,  4,  5,  6,  6,  8,  9, 25, 45, 47, 56, 57, 65, 75, 78, 89])

In [63]:
arr1= np.array([1,2,3,4,5,6,7,8,9])

In [64]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])